setup:
	@make build
	@make up 
	@make composer-update
build:
	docker-compose build --no-cache --force-rm
stop:
	docker-compose stop
up:
	docker-compose up -d
composer-update:
	docker exec laravel-docker bash -c "composer update"
data:
	docker exec laravel-docker bash -c "php artisan migrate"
	docker exec laravel-docker bash -c "php artisan db:seed"

# DB_CONNECTION=mysql
# DB_HOST=mysql_db
# DB_PORT=3406
# DB_DATABASE=laravel
# DB_USERNAME=root